### ISSUE TITLE
Happy 

### ISSUE THREAD

**Issue by samfry13-13** [meehawk/meehawk#10]
@meehawk lets chat
#3 @meehawk 

>

**Comment by KendallDoesCoding** [comment]
YOUR A BOT @meehawk

**Comment by meehawk** [comment]
Glad you loved the projects these are all OSS. I've been contributing to them for some time now. Are you active in open source too?

**Comment by KendallDoesCoding** [comment]
Not really @meehawk I make my own projects?

Why are you following all these ppl?

**Comment by meehawk** [comment]
We are building a beginner friendly community of developers who are recently active to raise more awareness about OSS and how to contribute and get started. I'll link it up here if you would be willing to help. @KendallDoesCoding what country are you from?

**Comment by meehawk** [comment]
I'll be adding multi-issue aggregation, theming support and a couple of other features to let's chat eventually sourcing it out to open source as a github-action. If anyone is willing to contribute to any of these feel free to hit me up. 

Note: This will likely break a lot of things in the current app

**Comment by KendallDoesCoding** [comment]
Oh ok. I'll check it out
