### ISSUE TITLE
docs: let's chat

### ISSUE THREAD

**Issue by meehawk** [meehawk/meehawk#3]
<h1 align="center">Leave a comment 💬 on the issue and get featured on my README 📖!</h1>

<p align="center">
  <img src="https://user-images.githubusercontent.com/80167324/129272507-69a64e18-000f-4dbf-8711-cea4f08c7ba9.gif" alt="TypingJimCarreyGIF]" />
</p>

_Chat theme thanks to [this](https://codepen.io/hussard/pen/ExgbXMP) awesome pen!_

**Comment by meehawk** [comment]
Hello, world!

**Comment by meehawk** [comment]
It's live!

**Comment by juampi20** [comment]
Awesome chat! 🎉

**Comment by gianca1994** [comment]
Hello 🤘🤘

**Comment by meehawk** [comment]
Hi @juampi20 thank you so much! Hola @gianca1994, hope you're having a wonderful weekend

**Comment by Mugdha-Hazra** [comment]
it's damn amazing!!

**Comment by meehawk** [comment]
Haha thank you much @Mugdha-Hazra 🧑‍💻

**Comment by vidhi-mody** [comment]
git: committed for life :)

**Comment by meehawk** [comment]
Nice pun there @vidhi-mody 😆

**Comment by tashakim** [comment]
Hello world hello everybahdy !

**Comment by boredland** [comment]
Hi there!

**Comment by meehawk** [comment]
Hola @tashakim, @boredland ! Hope folks are safe and sound!

**Comment by abd-ar** [comment]
Hello.

**Comment by PrijalBista** [comment]
Hello @meehawk . Very cool project :tada:

**Comment by hamiecod** [comment]
hii

**Comment by Sreehari521** [comment]
Hello World

**Comment by yordanzhelevdev** [comment]
Hello

**Comment by meehawk** [comment]
Thank you so much @PrijalBista

**Comment by meehawk** [comment]
Hey @hamiecod, @Sreehari521, @yordanzhelevdev I'd love to know what projects you folks have been working on!

**Comment by hamiecod** [comment]
I am currently learning nest.js

**Comment by Sreehari521** [comment]
> Hey @hamiecod, @Sreehari521, @yordanzhelevdev I'd love to know what projects you folks have been working on!

I am currently working on creating tutorials in Educational-Websites(An organization), link here:https://github.com/Educational-Websites

**Comment by meehawk** [comment]
That's interesting @hamiecod, Nestjs is an amazing framework. I've come to love it over traditional express! @Sreehari521 that's an interesting initiative, are you one of the tutors here?

**Comment by hamiecod** [comment]
@meehawk When did you start to program?

**Comment by hamiecod** [comment]
I think that nest.js has a lot more to offer that express.js, though I haven't read much nest.js docs yet. What's your say on it @meehawk and anybody else

**Comment by srinikesh2929** [comment]
Hi👋

**Comment by meehawk** [comment]
@hamiecod I've been coding for 5 years now! Nest.js is amazing for building microservices and structured backend. I've recently used it in a side project with gRPC and love it. I dont like the Angularesque code structure pattern though!

**Comment by hamiecod** [comment]
5 years! Thats amazing!

**Comment by gianca1994** [comment]
hey! I invite you to try this black jack that we released last night! If you like it, give it a star, that would help us a lot !! repository: https://github.com/kbiters/blackjack-js

**Comment by gianca1994** [comment]
@boredland @yordanzhelevdev @tashakim @PrijalBista @hamiecod @abd-ar @Mugdha-Hazra @vidhi-mody @Sreehari521 @srinikesh2929

Hey! I invite you to try this black jack that we released last night! If you like it, give it a star, that would help us a lot !! Repository: https://github.com/kbiters/blackjack-js

**Comment by chakrabortysayantan699** [comment]
Hi👋🏽   I am a beginner in the era of Open Source  projects how should I start my journey

**Comment by meehawk** [comment]
Hi @chakrabortysayantan699, I think the best place to start is to identify an organisation/project that you use and would love to contribute too. Try to find the issues labelled as `good first issue` or checkout the CONTRIBUTING.md file if the repo has one. If nothing works out, you can even reach out to the developers on their IRC

**Comment by danny-1k** [comment]
01110111 01101000 01100001 01110100 00100111 01110011 00100000 01100100 01101111 01110111 01101110 00100000 01100110 01101111 01101100 01101011 01110011

**Comment by flancast90** [comment]
Nice @danny-1k, What's Down to you, too! Cool chat, btw! Any projects anyone wants to share, and I'll share mine back!

**Comment by Coder-Liuu** [comment]
Hi, that's cool. 😆

**Comment by meehawk** [comment]
Too good @danny-1k ! Yo @flancast90 I'd love to know what you're working on! I've been working on actix, a Rust backend library

**Comment by flancast90** [comment]
Nice @meehawk! I'm currently working on my Chrome Extension [gitmbed](https://github.com/flancast90/gitmbed), and will soon push my spotify CLI for changing explicit content/songs.

**Comment by danny-1k** [comment]
@flancast90 Hey. I'm currently working on a deep learning framework made from scratch with numpy

**Comment by flancast90** [comment]
Awesome! I've started some projects like that, but never got around to finishing them. Mainly, it's hard for me to learn that kind of stuff because I'm still in High School, so anything I do I have to teach myself. Would you care to collaborate on a music generation program I started (numpy) if I add you to the private repo?
All that needs to be done is the actual training and the code to do that. I have developed a useful file structure for it that already makes the dataset.

**Comment by danny-1k** [comment]
@flancast90 That'll be damn cool. Dm me on IG (danny_1k)
btw, I'm also a High School student

**Comment by flancast90** [comment]
awesome @danny-1k, I just invited you as a collaborator (repo is called Eberl). I don't have Insta, so I mainly chat on GitHub or via direct text msg. 
Also, was looking at your repos, the Collatz Conjecture one (3x+1) was really interested, it's something I've always been really interested in. Into prime numbers, too, btw? I have a algorithm I wrote to find them faster than most of the sieves: https://github.com/flancast90/Colander

**Comment by danny-1k** [comment]
@flancast90 Your algorithm is really interesting
And no, I'm not really too much of a fan of prime numbers, although I do like Math

**Comment by flancast90** [comment]
@danny-1k, that's too bad, I find primes really interesting personally. Glad you found the algo interesting though! Can't wait to see what you can do with the Eberl Neural Net! I'll start a discussion there so we can talk more.

**Comment by uraninite** [comment]
Wow, readme.md is so cool ✨

**Comment by flancast90** [comment]
Yeah, @uraninite, I'll have to agree with you there. Very creative idea to apply GitHub actions like @meehawk did! What have you been working on lately?

**Comment by uraninite** [comment]
We are working on cryptography. What about you @flancast90?

**Comment by uraninite** [comment]
Nice work.

Actually, we will need all type of cryptographic methods for a better security. Currently we are using two types of cryptographic algorithms for a login system 🔑 without server based check; symmetric and asymmetric.

**Comment by flancast90** [comment]
Interesting. Are you saying you're not using any server at all, or that your first check is just serverless? If so, I wrote a serverless login system a while back all based on encryption, but never had a real use for it. For the heck of it I might just revamp it and share!

**Comment by 3kh0** [comment]
Hi Github! Visit my dumb website that earns me a penny every day: [https://3kh0.github.io](https://3kh0.github.io/)

**Comment by flancast90** [comment]
lol @3kh0, loved the fake virus screen! Even a penny a day can add up! Keep at the programming!

**Comment by 3kh0** [comment]
> lol @3kh0, loved the fake virus screen! Even a penny a day can add up! Keep at the programming!

Thank you for the feedback. That really means a lot to me!

**Comment by hamiecod** [comment]
@meehawk may I implement something similar to your cyberspace in my Readme? ^-^

**Comment by MasterCoder1234567890** [comment]
Hi! I Am Aaryan! Any Indians Here? 
If Yes, Then Namaste to all!

**Comment by MasterCoder1234567890** [comment]
Hello!!!

**Comment by MasterCoder1234567890** [comment]
Vey Nice!

**Comment by MasterCoder1234567890** [comment]
@meehawk Can I Use This In My Readme? Pleeeeeaseeee I Will Mention You In The Credits

**Comment by meehawk** [comment]
@MasterCoder1234567890 @hamiecod I am going to open source the functionality to a github-actions pretty soon. Expect a launch this week. Would that help?

**Comment by hamiecod** [comment]
> @MasterCoder1234567890 @hamiecod I am going to open source the functionality to a github-actions pretty soon with a lot more functionalities. Expect a launch this week. Would that help?

That would be really helpful 😃. Thanks!

**Comment by Sreehari521** [comment]
> Hi! I Am Aaryan! Any Indians Here?
> If Yes, Then Namaste to all!

Namaste @MasterCoder1234567890

**Comment by 3kh0** [comment]
@meehawk Why is this an issue? not a discussion.

**Comment by meehawk** [comment]
@3kh0 Just keeping it old school. The os implementation would default to a discussion though

**Comment by 3kh0** [comment]
> @3kh0 Just keeping it old school. The os implementation would default to a discussion though

oh I see. 

Quick question how many sides does a circle have?

**Comment by meehawk** [comment]
@3kh0 infinite I guess

**Comment by flancast90** [comment]
Isn't it obvious? Depending on who you talk to, you will hear infinite, 0, and I've heard several well-respected professors make arguments for something in the 65k+range using the brute-force method.

**Comment by flancast90** [comment]
The real question is: is 0.999... = 1? I think so, and I bet you can't prove me wrong!

If you still don't believe me, here is a proof:
0.333... = 1/3
0.333...*3 = 0.999...
1/3*3 = 1
Therefore, 0.999... = 1

**Comment by 3kh0** [comment]
![image](https://user-images.githubusercontent.com/58097612/132565299-5f1996cb-f8a0-439e-8b6d-1ad0a077c08a.png)
amazing

**Comment by AstroOrbis** [comment]
ovo

**Comment by Painadath** [comment]
Hi @meehawk are u in discord or gitter?

**Comment by meehawk** [comment]
Hi @Painadath yes I am on discord

**Comment by 3kh0** [comment]
I have discord 3kh0_#6969

> Hi @Painadath yes I am on discord

**Comment by Painadath** [comment]
> Hi @Painadath yes I am on discord

Id?

**Comment by meehawk** [comment]
@Painadath its `Con D. Oriano#0055`

**Comment by elolelo** [comment]
@meehawk  hello, very cool project! And  I have took the liberty of leaving you a note on discord

**Comment by lingsv** [comment]
Hello!!

**Comment by 3kh0** [comment]
> Hello!!

hi

**Comment by AstroOrbis** [comment]
Hello a l l

**Comment by 3kh0** [comment]
> Hello a l l

hello

**Comment by Abhinav-CHD** [comment]
Hello everyone, good to be here!

**Comment by 3kh0** [comment]
> Hello everyone, good to be here!

Hello there! I make really bad games

**Comment by Asher-MS** [comment]
Hello Everybody!!!!!!!!!!!!!!!

**Comment by loralighte** [comment]
Bonjour

**Comment by meehawk** [comment]
Hi everyone! @elolelo I did not receive any messages?

**Comment by Hyperion101010** [comment]
Hi @meehawk  awesome open source contributions and readme!

**Comment by dTONCAO** [comment]
![received_4217384431642589.jpeg](https://user-images.githubusercontent.com/90931373/133917329-09167dc5-8093-4a73-93e1-756af218f5e1.jpeg)

**Comment by karthik558** [comment]
❤️❤️

**Comment by vidhi-mody** [comment]
I may think in binary, but you're the only 1! ¯\ (ツ) /¯

**Comment by 3kh0** [comment]
does anyone know css?

**Comment by era2010-coder** [comment]
Hello

**Comment by karthik558** [comment]
> does anyone know css?

i know , ssup ??

**Comment by flancast90** [comment]
> I just made a little splash text that changes with every page load. Could I have some feedback?
> 
> [My website](https://3kh0.github.io/)

Cool! Loved the scavenger hunt btw. Almost done solving it (I think)

**Comment by Borrus-sudo** [comment]
Hey meehaw!

**Comment by Deniied** [comment]
is this the SUS imposter from AMONG US!?

**Comment by loralighte** [comment]
Our Kansas

**Comment by abhishek-singh77** [comment]
Hello, feels good to be part of it :-)

**Comment by Nicola-Bini** [comment]
Hello @meehawk!
The GUI is inspired from XCOM, right? That's so cool!

**Comment by 3kh0** [comment]
hi

**Comment by PQCraft** [comment]
<img src="https://c.tenor.com/kHcmsxlKHEAAAAAM/rock-one-eyebrow-raised-rock-staring.gif"></img>

**Comment by hoshiya4522** [comment]
Loved the cyberpunk theme!

**Comment by LuizRicardoCarvalho** [comment]
hello friend!! :)

**Comment by jascha030** [comment]
Now **_this_** is a README! (Or READMEE rather) 🥇

**Comment by kataya1** [comment]
Amazing work, and thanks for the follow 😊

**Comment by meehawk** [comment]
Hi @tnborn the best way to start would be to build a project. It can be as simple as a single page website or a full fledged application. If you want to get in a specific project and if that project is taking contributions, you can reach out to people on the IRC of that project or try to find issues tagged as `good first issue` to kind of filter out on beginner friendly issues. The open source community is generally quite welcoming and you'd most definitely find help when working on a project

**Comment by Password-Classified** [comment]
Hi! This is so cool! How does this work? Love the theme.

**Comment by bobbyg603** [comment]
Thanks for the follow - just returned the favor! 🚀

**Comment by samfry13-13** [comment]
How do I open/find my private respiratories

**Comment by Password-Classified** [comment]
> Thanks for the follow - just returned the favor! 🚀

Same! I can't believe someone with 5.8k followers would follow me!

**Comment by Nicola-Bini** [comment]
@Password-Classified @bobbyg603 
Remember guys, someone's illusion is someone's else reality

**Comment by meehawk** [comment]
@Password-Classified actually it's a very neat trick. I use githubs API to fetch all the comments on this issue and that gets rendered into the chat which is followed by Puppeteer taking an SS. You can check out the code on how it works. This reminds @Nicola-Bini the issue with your graph is that you got to screenshot the rendered Page with Puppeteer and set vercel to no cache so that it gives you a fresh screen shot each time

**Comment by meehawk** [comment]
> How do I open/find my private respiratories

I didn't get your question. You can use the filter on the top to just show repositories of yours which are private.

**Comment by jmrchelani** [comment]
great

**Comment by Hacksore** [comment]
👁👄👁

**Comment by craftycatz** [comment]
Very cool!

**Comment by blopawitt** [comment]
Hello from Brazil!

**Comment by neilitalia** [comment]
Awesome project 🎉

**Comment by Hacksore** [comment]
Been working on a new project. Feel free to take a look if you’re an avid discord user as it might be of some interest.

https://github.com/Hacksore/overlayed

I didn't mention it in my last comment but really cool project @meehawk 🎉🎉🎉

**Comment by yusiflinurlan** [comment]
Hello from Baku

**Comment by meehawk** [comment]
Holla people, we are shifting to Github discussions based on a prior suggestion. Keep the chat rolling!
