### ISSUE TITLE
Retrieve image from website

### ISSUE THREAD

**Issue by Nicola-Bini** [meehawk/meehawk#9]
Hi @meehawk,

I have been trying to replicate what you did to update a graph in my readme. I managed to connect a vercel app to a github repository to update the image on the website automatically, however:

- Are you continuously committing to a repository to update your website? or are you using a cleaner way (e.g. github actions)
- I can't manage to retrieve the image from my app: https://test-rep-jade.vercel.app/ I tried <"img src="https://test-rep-jade.vercel.app/"> but it's clearly missing something

ps: you had a great idea!

**Comment by meehawk** [comment]
@Nicola-Bini is your code open?  If so I can take a look.

**Comment by Nicola-Bini** [comment]
Here it is:
https://github.com/Nicola-Bini/test-rep

**Comment by meehawk** [comment]
@Nicola-Bini were you able to solve this issue?

**Comment by Nicola-Bini** [comment]
Hi @meehawk, I paused the project because I have some upcoming deadlines. However, I think now I understood how it works and I should be able to fix it without fail. Thank you!
